PAPP-25307: Cherwell SaaS compatibility
splunk-soar-connectors/cherwell pull request #2
Opened 2022-04-13 11:15 UTC by pdesai-crest

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2022-04-19 10:51 UTC, mmomin-crest commented on cherwell_connector.py
>              soup = BeautifulSoup(response.text, "html.parser")
Add the below script to remove unnecessary things from HTML response

# Remove the script, style, footer and navigation part from the HTML message
	for element in soup(["script", "style", "footer", "nav"]):
		element.extract()

2022-04-19 10:56 UTC, mmomin-crest commented on cherwell_connector.py
>              exit(1)
Instead of `exit() ` please use `sys.exit()` for smooth exiting from code.

2022-04-19 10:58 UTC, mmomin-crest commented on cherwell_connector.py
Please add `verify` as an argument.

2022-05-16 14:02 UTC, pdesai-crest commented on cherwell_connector.py
>              soup = BeautifulSoup(response.text, "html.parser")
Updated

2022-06-14 09:47 UTC, dhwanis-crest approved these changes

2022-06-15 03:46 UTC, dvora-crest requested changes

2022-06-15 03:46 UTC, dvora-crest commented on release_notes/unreleased.md
> +* Update Authentication Workflow
Should we update it to "Updated authentication workflow to utilize refresh token"?

2022-06-15 03:46 UTC, dvora-crest commented on release_notes/unreleased.md
> +* Update Authentication Workflow
Should we update it to "Updated authentication workflow to utilize refresh token"?

2022-06-15 03:46 UTC, dvora-crest commented on cherwell_connector.py
> +                self.debug_print("Unable to make encryption Error:{}".format(error_message))
Can we change the message to "Error occurred while encrypting the token: {}".format(error_message)?

2022-06-15 03:46 UTC, dvora-crest commented on cherwell_connector.py
> +                self.debug_print("Unable to make encryption Error:{}".format(error_message))
Can we change the message to "Error occurred while encrypting the token: {}".format(error_message)"?

2022-06-15 03:46 UTC, dvora-crest commented on cherwell_connector.py
> +                self.debug_print("Unable to make decryption. Error:{0}".format(error_message))
Can we change the message to "Error occurred while decrypting the token: {}".format(error_message)?

2022-06-15 03:46 UTC, dvora-crest commented on cherwell_connector.py
> +                self.debug_print("Unable to make decryption. Error:{0}".format(error_message))
Can we change the message to "Error occurred while decrypting the token: {}".format(error_message)?

2022-06-15 03:48 UTC, dvora-crest approved these changes

2022-10-12 10:23 UTC, pdesai-crest commented
We will be releasing this app as community since our asset stopped working.

**Reason for pipeline failures.**
- Static tests are failing because minimum phantom version is kept at 5.2.0 instead of the required 5.3.4 because we tested this app on v5.2.0 before our asset got expired.
- Integration and static tests are failing because of the same issue with our asset.

2022-10-12 11:57 UTC, dgopani-crest approved these changes

2022-10-13 03:00 UTC, gary-phantom approved these changes

2022-10-13 03:43 UTC, splunk-jessica requested changes

2022-10-13 03:43 UTC, splunk-jessica commented on cherwell_connector.py
> +            print("Unable to get session id from the platfrom. Error: " + str(e))
```suggestion
            print("Unable to get session id from the platform. Error: " + str(e))
```

2022-10-13 05:14 UTC, pdesai-crest commented on cherwell_connector.py
> +            print("Unable to get session id from the platfrom. Error: " + str(e))
Fixed the typo

2022-10-13 16:36 UTC, splunk-jessica approved these changes

2022-10-14 06:49 UTC, merged